// Copyright 2022 Stefan Kerkmann
// SPDX-License-Identifier: GPL-2.0-or-later

#pragma once


// #define DEBUG_MATRIX_SCAN_RATE

// #define QMK_WAITING_TEST_BUSY_PIN GP8
// #define QMK_WAITING_TEST_YIELD_PIN GP9

#define RP2040_BOOTLOADER_DOUBLE_TAP_RESET
#define RP2040_BOOTLOADER_DOUBLE_TAP_RESET_LED GP16
#define RP2040_BOOTLOADER_DOUBLE_TAP_RESET_TIMEOUT 500U
#define USB_SUSPEND_WAKEUP_DELAY 200
#define BOTH_SHIFTS_TURNS_ON_CAPS_WORD
#define TAPPING_TERM 190
#undef RGB_DI_PIN
#define RGB_DI_PIN GP16
#define WS2812_DI_PIN GP16
#undef RGBLED_NUM
#define RGBLED_NUM 2
#undef RGBLED_SPLIT
#define RGBLED_SPLIT {1, 1}
//#define COMBO_COUNT 2
