# OLED_ENABLE = yes
# OLED_DRIVER = SSD1306

#WS2812_DRIVER = vendor

CAPS_WORD_ENABLE = yes
TAP_DANCE_ENABLE = yes
SERIAL_DRIVER = vendor
RGBLIGHT_ENABLE = yes
RGBLIGHT_DRIVER = WS2812
WS2812_DRIVER = vendor
SEND_STRING_ENABLE = yes
#IGNORE_MOD_TAP_INTERRUPT= yes
#COMBO_ENABLE = yes
